# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: angularCliVersion
    type: string
  - name: cleanBuild
    type: boolean
steps:
- bash: |
        echo "Work Directory@@@@@@@@@@@@@@@@@@"
        echo $(System.DefaultWorkingDirectory)  
        set -e
        node --version
        npm --version
        echo "npm cache location"
        npm config get cache
        echo "cleaning up workspace"
        rm -rf .angular
        rm -rf build
        rm -rf dist 
  #ToDo:Upload result of lint to sonarqube. (Use several rules in config file).
  displayName: 'Cleanup NPM Cache & Workspace'

- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'TataSaaS'
    sourceRepo: 'san-npm'
    workingFolder: '$(System.DefaultWorkingDirectory)'
    arguments: '--prefer-offline --audit=false --no-audit'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: JFrogNpm@1
  displayName: 'JFrog AngularCli Install'
  inputs:
    command: 'ci'
    artifactoryConnection: 'TataSaaS'
    sourceRepo: 'san-npm'
    workingFolder: '$(System.DefaultWorkingDirectory)'
    arguments: '--prefer-offline --audit=false --no-audit'
    collectBuildInfo: false
    threads: '1'
    buildName: 'digital-npm-$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'    
    includeEnvVars: false
