# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
        echo "Work Directory@@@@@@@@@@@@@@@@@@"
        echo $(System.DefaultWorkingDirectory) 
        set -e
        node --version
        npm --version
        echo "npm cache location"
        npm config get cache
        echo "cleaning up workspace"
        rm -rf .angular
        rm -rf build
        rm -rf dist 
  #ToDo:Upload result of lint to sonarqube. (Use several rules in config file).
  displayName: 'Cleanup NPM Cache & Workspace'
- task: JFrogNpm@1
  inputs:
    command: 'ci'
    artifactoryConnection: 'TataSaaS'
    sourceRepo: 'san-npm'
    workingFolder: '$(System.DefaultWorkingDirectory)'
    arguments: '-g --prefer-offline --audit=false --no-audit'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'TataSaaS'
    sourceRepo: 'san-npm'
    workingFolder: '$(System.DefaultWorkingDirectory)'
    arguments: '$(System.DefaultWorkingDirectory)'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

#- task: CopyFiles@2
#  inputs:
#    sourceFolder: '$(Build.SourcesDirectory)'
#    contents: '*.tgz' 
#    targetFolder: $(Build.ArtifactStagingDirectory)/npm
#  displayName: 'Copy npm package'

#- task: CopyFiles@2
#  inputs:
#    sourceFolder: '$(Build.SourcesDirectory)'
#    contents: 'package.json' 
#    targetFolder: $(Build.ArtifactStagingDirectory)/npm
#  displayName: 'Copy package.json'   

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'TataSaaS'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'TataXraySaaS'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
    vuln: true
